auth:
  clientId: xyz-123
  jwtDuration: 1 # Minutes
  server:
    url: http://localhost:${mock.server.port}/get-jwt

external:
  clientId: xyz-123
  api:
    url: http://localhost:${mock.server.port}/api